### PR TITLE
Fixes: Netbox 4.0 breaking change

### PR DESCRIPTION
**Pull request by tardoe**
Renames device.device_role to device.role. This fixes adds logic to handle this change across Netbox versions.

### CODE REVIEW

**Review by radaelbroko — COMMENTED** [review]
I'm running Netbox 4.0.5 and with this change works for me. Thanks!

**Comment by tardoe** [comment]
@bortok Have you got a moment to review this one?

**Comment by bortok** [comment]
@tardoe sorry for the delay, I'm traveling this month. The reason I didn't merge it right away is the need to bump netbox versions in the CI environment to test with 4.0.

**Comment by bortok** [comment]
Hi @tardoe, I'm working on this. Could you please cancel this PR and make a new one with `dev` branch as a target? Thank you and sorry for the delay.

**Review by bortok — APPROVED** [review]
tested with NB v4.0

**Pull request merged**
